name: lint

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

env:
  UV_PYTHON: 3.14

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: |
        uv sync --dev
    - name: Lint
      run: |
        source .venv/bin/activate
        make lint
